internal_server_error:
  value: 
    code: 1001
    message: 'network error'
    data: {}
    trace:
      - line: 50